# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Shobhit Agarwal
tagline:             'Android and Python Developer'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://www.github.com/shobhitagarwal1612
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Shobhit Agarwal
  url:               https://twitter.com/mdo
  email:             shobhitagarwal1612@gmail.com

# Custom vars
version:             1.0.0
