# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Shobhit's Blog
tagline:             'Android and Python Developer'
description:         'Open Source Lover'
url:                 https://www.github.com/shobhitagarwal1612
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Shobhit Agarwal
  url:               https://twitter.com/mdo
  email:             shobhitagarwal1612@gmail.com

# Custom vars
version:             1.0.0
